# Configurações gerais do Spring Boot
spring:
  # Nome da aplicação
  application:
    name: rest-with-sprong-boot-and-java-luke

  # Configurações do banco de dados
  datasource:
    # Driver JDBC para MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    # URL de conexão com o banco de dados
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_luke?useTimezone=true&serverTimezone=UTC
    # Credenciais do banco de dados
    username: root
    password: Akatsuki_314152

  # Configurações do JPA (Java Persistence API)
  jpa:
    # Mostrar as consultas SQL no console (útil para depuração)
    show-sql: false

    hibernate:
      # Estratégia de atualização do banco de dados
      ddl-auto: update

    # Configurações específicas do Hibernate (Ative se for usar o dialeto)
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.MySQL8Dialect